language: java
jdk:
 - oraclejdk8
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: moskilla

services:
  - postgresql
before_script:
  - psql -c 'create database postgres;' -U postgres